numFits = 100;
numExp = 8;
numTrials = 1000;

%   SSA_Linspace and Norm_Linspace_LNA are datasets generated respectively
%   from normally distributed data and from data generated by an SSA
%   directly. Each defaults to the LinSpace optimality setting, which is by
%   default semi-linearly spaced (though the density of experiments is
%   twice as large in the bistable region, simply due to how the SSA data
%   was generated). We compare this to the Ds-Optimal and D-Optimally
%   distributed data, which is generated based off of an OED procedure.

% spmd
%    if labindex==1
%         optionsA1 = struct('DataSource','SSA','SystemSize',90,'Optimality','LinSpace');
%         [nanA1,fitsA1] = generateFits(numFits,numExp,numTrials,optionsA1);
%         dlmwrite('./1D_Michael/Data/1000x8__SSA_LinSpace_90.txt',fitsA1,'-append','delimiter','\t');
%         dlmwrite('./1D_Michael/Data/1000x8__SSA_LinSpace_90_nans.txt',nanA1,'-append','delimiter','\t');
%         
%         optionsB1 = struct('DataSource','SSA','SystemSize',90,'Optimality','Ds_Optimal');
%         [nanB1,fitsB1] = generateFits(numFits,numExp,numTrials,optionsB1);
%         dlmwrite('./1D_Michael/Data/1000x8__SSA_Ds_90.txt',fitsB1,'-append','delimiter','\t');
%         dlmwrite('./1D_Michael/Data/1000x8__SSA_Ds_90_nans.txt',nanB1,'-append','delimiter','\t');
%    elseif labindex==2
%         optionsC1 = struct('DataSource','SSA','SystemSize',90,'Optimality','D_Optimal');
%         [nanC1,fitsC1] = generateFits(numFits,numExp,numTrials,optionsC1);
%         dlmwrite('./1D_Michael/Data/1000x8__SSA_D_90.txt',fitsC1,'-append','delimiter','\t');
%         dlmwrite('./1D_Michael/Data/1000x8__SSA_D_90_nans.txt',nanC1,'-append','delimiter','\t');
%         
%         optionsA21 = struct('DataSource','Normal','SystemSize',90,'Optimality','LinSpace');
%         [nanA21,fitsA21] = generateFits(numFits,numExp,numTrials,optionsA21);
%         dlmwrite('./1D_Michael/Data/1000x8__Normal_LinSpace_90.txt',fitsA21,'-append','delimiter','\t');
%         dlmwrite('./1D_Michael/Data/1000x8__Normal_LinSpace_90_nans.txt',nanA21,'-append','delimiter','\t');
%    elseif labindex==3
%         optionsB21 = struct('DataSource','Normal','SystemSize',90,'Optimality','Ds_Optimal');
%         [nanB21,fitsB21] = generateFits(numFits,numExp,numTrials,optionsB21);
%         dlmwrite('./1D_Michael/Data/1000x8__Normal_Ds_90.txt',fitsB21,'-append','delimiter','\t');
%         dlmwrite('./1D_Michael/Data/1000x8__Normal_Ds_90nans.txt',nanB21,'-append','delimiter','\t');
%    elseif labindex==4
%         optionsC21 = struct('DataSource','Normal','SystemSize',90,'Optimality','D_Optimal');
%         [nanC21,fitsC21] = generateFits(numFits,numExp,numTrials,optionsC21);
%         dlmwrite('./1D_Michael/Data/1000x8__Normal_D_90.txt',fitsC21,'-append','delimiter','\t');
%         dlmwrite('./1D_Michael/Data/1000x8__Normal_D_90_nans.txt',nanC21,'-append','delimiter','\t');
%    end
% end

spmd
   if labindex==1
        optionsA2 = struct('DataSource','SSA','SystemSize',60,'Optimality','LinSpace');
        [nanA2,fitsA2] = generateFits(numFits,numExp,numTrials,optionsA2);
        dlmwrite('./1D_Michael/Data/1000x8__SSA_LinSpace_60.txt',fitsA2,'-append','delimiter','\t');
        dlmwrite('./1D_Michael/Data/1000x8__SSA_LinSpace_60_nans.txt',nanA2,'-append','delimiter','\t');
        
        optionsB2 = struct('DataSource','SSA','SystemSize',60,'Optimality','Ds_Optimal');
        [nanB2,fitsB2] = generateFits(numFits,numExp,numTrials,optionsB2);
        dlmwrite('./1D_Michael/Data/1000x8__SSA_Ds_60.txt',fitsB2,'-append','delimiter','\t');
        dlmwrite('./1D_Michael/Data/1000x8__SSA_Ds_60_nans.txt',nanB2,'-append','delimiter','\t');
   elseif labindex==2
        optionsC2 = struct('DataSource','SSA','SystemSize',60,'Optimality','D_Optimal');
        [nanC2,fitsC2] = generateFits(numFits,numExp,numTrials,optionsC2);
        dlmwrite('./1D_Michael/Data/1000x8__SSA_D_60.txt',fitsC2,'-append','delimiter','\t');
        dlmwrite('./1D_Michael/Data/1000x8__SSA_D_60_nans.txt',nanC2,'-append','delimiter','\t');
        
        optionsA22 = struct('DataSource','Normal','SystemSize',60,'Optimality','LinSpace');
        [nanA22,fitsA22] = generateFits(numFits,numExp,numTrials,optionsA22);
        dlmwrite('./1D_Michael/Data/1000x8__Normal_LinSpace_60.txt',fitsA22,'-append','delimiter','\t');
        dlmwrite('./1D_Michael/Data/1000x8__Normal_LinSpace_60_nans.txt',nanA22,'-append','delimiter','\t');
   elseif labindex==3
        optionsB22 = struct('DataSource','Normal','SystemSize',60,'Optimality','Ds_Optimal');
        [nanB22,fitsB22] = generateFits(numFits,numExp,numTrials,optionsB22);
        dlmwrite('./1D_Michael/Data/1000x8__Normal_Ds_60.txt',fitsB22,'-append','delimiter','\t');
        dlmwrite('./1D_Michael/Data/1000x8__Normal_Ds_60nans.txt',nanB22,'-append','delimiter','\t');
   elseif labindex==4
        optionsC22 = struct('DataSource','Normal','SystemSize',60,'Optimality','D_Optimal');
        [nanC22,fitsC22] = generateFits(numFits,numExp,numTrials,optionsC22);
        dlmwrite('./1D_Michael/Data/1000x8__Normal_D_60.txt',fitsC22,'-append','delimiter','\t');
        dlmwrite('./1D_Michael/Data/1000x8__Normal_D_60_nans.txt',nanC22,'-append','delimiter','\t');
   end
end

% spmd
%    if labindex==1
%         optionsA3 = struct('DataSource','SSA','SystemSize',120,'Optimality','LinSpace');
%         [nanA3,fitsA3] = generateFits(numFits,numExp,numTrials,optionsA3);
%         dlmwrite('./1D_Michael/Data/1000x8__SSA_LinSpace_120.txt',fitsA3,'-append','delimiter','\t');
%         dlmwrite('./1D_Michael/Data/1000x8__SSA_LinSpace_120_nans.txt',nanA3,'-append','delimiter','\t');
%         
%         optionsB3 = struct('DataSource','SSA','SystemSize',120,'Optimality','Ds_Optimal');
%         [nanB3,fitsB3] = generateFits(numFits,numExp,numTrials,optionsB3);
%         dlmwrite('./1D_Michael/Data/1000x8__SSA_Ds_120.txt',fitsB3,'-append','delimiter','\t');
%         dlmwrite('./1D_Michael/Data/1000x8__SSA_Ds_120_nans.txt',nanB3,'-append','delimiter','\t');
%    elseif labindex==2
%         optionsC3 = struct('DataSource','SSA','SystemSize',120,'Optimality','D_Optimal');
%         [nanC3,fitsC3] = generateFits(numFits,numExp,numTrials,optionsC3);
%         dlmwrite('./1D_Michael/Data/1000x8__SSA_D_120.txt',fitsC3,'-append','delimiter','\t');
%         dlmwrite('./1D_Michael/Data/1000x8__SSA_D_120_nans.txt',nanC3,'-append','delimiter','\t');
%         
%         optionsA23 = struct('DataSource','Normal','SystemSize',120,'Optimality','LinSpace');
%         [nanA23,fitsA23] = generateFits(numFits,numExp,numTrials,optionsA23);
%         dlmwrite('./1D_Michael/Data/1000x8__Normal_LinSpace_120.txt',fitsA23,'-append','delimiter','\t');
%         dlmwrite('./1D_Michael/Data/1000x8__Normal_LinSpace_120_nans.txt',nanA23,'-append','delimiter','\t');
%    elseif labindex==3
%         optionsB23 = struct('DataSource','Normal','SystemSize',120,'Optimality','Ds_Optimal');
%         [nanB23,fitsB23] = generateFits(numFits,numExp,numTrials,optionsB23);
%         dlmwrite('./1D_Michael/Data/1000x8__Normal_Ds_120.txt',fitsB23,'-append','delimiter','\t');
%         dlmwrite('./1D_Michael/Data/1000x8__Normal_Ds_120nans.txt',nanB23,'-append','delimiter','\t');
%    elseif labindex==4
%         optionsC23 = struct('DataSource','Normal','SystemSize',120,'Optimality','D_Optimal');
%         [nanC23,fitsC23] = generateFits(numFits,numExp,numTrials,optionsC23);
%         dlmwrite('./1D_Michael/Data/1000x8__Normal_D_120.txt',fitsC23,'-append','delimiter','\t');
%         dlmwrite('./1D_Michael/Data/1000x8__Normal_D_120_nans.txt',nanC23,'-append','delimiter','\t');
%    end
% end